macro(kinectfusion_configure_linker project_name)
  set(KINECTFUSION_USER_LINKER_OPTION
    "DEFAULT"
      CACHE STRING "Linker to be used")
    set(KINECTFUSION_USER_LINKER_OPTION_VALUES "DEFAULT" "SYSTEM" "LLD" "GOLD" "BFD" "MOLD" "SOLD" "APPLE_CLASSIC" "MSVC")
    set_property(CACHE KINECTFUSION_USER_LINKER_OPTION PROPERTY STRINGS ${KINECTFUSION_USER_LINKER_OPTION_VALUES})
  list(
    FIND
    KINECTFUSION_USER_LINKER_OPTION_VALUES
    ${KINECTFUSION_USER_LINKER_OPTION}
    KINECTFUSION_USER_LINKER_OPTION_INDEX)

  if(${KINECTFUSION_USER_LINKER_OPTION_INDEX} EQUAL -1)
    message(
      STATUS
      "Using custom linker: '${KINECTFUSION_USER_LINKER_OPTION}', explicitly supported entries are ${KINECTFUSION_USER_LINKER_OPTION_VALUES}")
  endif()

  set_target_properties(${project_name} PROPERTIES LINKER_TYPE "${KINECTFUSION_USER_LINKER_OPTION}")
endmacro()
